# Makefile

TARGET = store

# Include standard template for this suite
-include ../../../../Makefile-asm.defaults
-include ../../../Makefile-asm.defaults
-include ../../Makefile-asm.defaults
-include ../Makefile-asm.defaults
